#!/bin/bash

############################################################
# dmenu_cmd - dmenu script that simulates 'rofi -show run' #
#             only insert command                          #
#                                                          #
# Author: dmesg00 <dmesg00@duck.com>                           #
# Last update: 20-11-2022                                  #
############################################################

# Configuration variables
load_theme_path="${HOME}/.dmenu"
load_themes="${load_theme_path}/themes"
load_theme_file="${load_theme_path}/load_theme"
font_dmenu="UbuntuMono Nerd Font-12"

function load_theme() {
  if [ -f "${load_theme_file}" ] ; then
    source "${load_theme_file}"
  else
    mkdir -p "${load_theme_path}"
    mkdir -p "${load_themes}"
    echo "#!/bin/bash" > ${load_theme_file} 
    echo "" >> ${load_theme_file} 
    echo "NFCOLOR=\"#bbbbbb\"" >> ${load_theme_file} 
    echo "NBCOLOR=\"#1f1f35\"" >> ${load_theme_file} 
    echo "SFCOLOR=\"#eeeeee\"" >> ${load_theme_file} 
    echo "SBCOLOR=\"#664477\"" >> ${load_theme_file}
    source "${load_theme_file}" 
  fi
}

function generate_spaces() {
  num_spaces=${1}
  count_spaces=1
  while [ ${count_spaces} -le ${num_spaces} ] ; do
    echo -n " "
    count_spaces=$(expr ${count_spaces} + 1)
  done
}

load_theme
command_run=$(generate_spaces 75 | dmenu -i -fn "${font_dmenu}" -nb "${NBCOLOR}" -nf "${NFCOLOR}" -sb "${SBCOLOR}" -sf "${SFCOLOR}" -l 18 -p " command:")
${command_run}
